services:
  - type: web
    name: Backend
    rootDir: backend
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
