# ============================
# Build stage
# ============================
FROM openjdk:21 AS build
WORKDIR /app
COPY . .
RUN chmod +x ./mvnw
RUN ./mvnw clean package -DskipTests

# ============================
# Runtime stage
# ============================
FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=build /app/target/hospital-ai-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]